# Creating SDSS dataset from SDSS DR15 Query

    --> http://skyserver.sdss.org/dr15/en/tools/search/sql.aspx

In [216]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
import warnings
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, normalize 
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
import timeit
import os
warnings.filterwarnings("ignore")

In [217]:
all_filenames = ['Test/SDSS/QSO.csv','Test/SDSS/GALAXY.csv','Test/SDSS/STAR.csv']
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "SDSS_combined.csv", index=False, encoding='utf-8-sig')

In [218]:
df = pd.read_csv('SDSS_combined.csv')

In [219]:
df = df.sample(frac = 1)
df.head()

,objid,ra,dec,u,g,r,i,z,run,rerun,camcol,field,specobjid,class,redshift,plate,mjd,fiberid
446,1.237650e+18,147.598924,0.738829,24.37392,21.18468,19.88617,19.58668,19.44231,756,301,5,212,4.309060e+18,QSO,4.054845,3827,55565,868
25239,1.237650e+18,114.610477,38.479947,24.44511,22.04980,20.31414,19.03393,18.18590,1350,301,3,52,4.128850e+18,STAR,0.000073,3667,55566,635
22696,1.237650e+18,60.479178,-4.556179,17.07993,16.11202,15.74807,15.57424,15.52180,1045,301,6,177,1.840990e+18,STAR,0.000463,1635,53053,528
14309,1.237650e+18,213.416752,-0.779284,22.66896,23.13755,21.33053,19.90508,19.38044,752,301,2,467,4.543220e+18,GALAXY,0.703412,4035,55383,781
11667,1.237650e+18,150.546783,1.196249,22.96747,21.86820,20.16143,19.25737,18.81125,756,301,6,232,4.311240e+18,GALAXY,0.459710,3829,55300,621

In [220]:
sdss_df = df
sdss_df

,objid,ra,dec,u,g,r,i,z,run,rerun,camcol,field,specobjid,class,redshift,plate,mjd,fiberid
446,1.237650e+18,147.598924,0.738829,24.37392,21.18468,19.88617,19.58668,19.44231,756,301,5,212,4.309060e+18,QSO,4.054845,3827,55565,868
25239,1.237650e+18,114.610477,38.479947,24.44511,22.04980,20.31414,19.03393,18.18590,1350,301,3,52,4.128850e+18,STAR,0.000073,3667,55566,635
22696,1.237650e+18,60.479178,-4.556179,17.07993,16.11202,15.74807,15.57424,15.52180,1045,301,6,177,1.840990e+18,STAR,0.000463,1635,53053,528
14309,1.237650e+18,213.416752,-0.779284,22.66896,23.13755,21.33053,19.90508,19.38044,752,301,2,467,4.543220e+18,GALAXY,0.703412,4035,55383,781
11667,1.237650e+18,150.546783,1.196249,22.96747,21.86820,20.16143,19.25737,18.81125,756,301,6,232,4.311240e+18,GALAXY,0.459710,3829,55300,621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,1.237650e+18,163.864576,-0.471311,19.50503,19.46745,19.15787,19.07567,19.11254,756,301,2,321,3.107650e+17,QSO,1.356743,276,51909,61
4087,1.237650e+18,203.469379,-1.026392,24.90191,22.27316,20.61410,20.43886,20.33940,756,301,1,585,4.555480e+18,QSO,4.044824,4046,55605,334
12926,1.237650e+18,211.496625,-0.757149,22.80613,21.98163,20.25640,19.45333,18.93341,752,301,2,454,4.545270e+18,GALAXY,0.485634,4037,55631,49
19450,1.237650e+18,221.192227,-0.661993,24.21974,21.69336,19.74878,18.83111,18.35311,752,301,2,519,4.528440e+18,GALAXY,0.528334,4022,55352,267
491,1.237650e+18,223.290116,0.564291,21.24560,20.52563,20.66317,20.70104,20.42698,752,301,5,533,4.525180e+18,QSO,2.361929,4019,55363,681

In [221]:
#Handling missing values
df = df.dropna()

# Preprocess Functions

In [222]:
sdss_df_fe = sdss_df

# encode class labels to integers
le = LabelEncoder()
y_encoded = le.fit_transform(sdss_df_fe['class'])
sdss_df_fe['class'] = y_encoded

# Principal Component Analysis
pca = PCA(n_components=4)
ugriz = pca.fit_transform(sdss_df_fe[['u', 'g', 'r', 'i', 'z']])

# update dataframe 
sdss_df_fe = pd.concat((sdss_df_fe, pd.DataFrame(ugriz)), axis=1)
sdss_df_fe.rename({0: 'PCA_1', 1: 'PCA_2',2: 'PCA_3',3:'PCA_4'}, axis=1, inplace = True)
sdss_df_fe.drop(['u', 'g', 'r', 'i', 'z'], axis=1, inplace=True)
sdss_df_fe.head()

In [223]:
sdss_df_fe = sdss_df_fe.sample(frac=1)

In [224]:
sdss_df_fe.to_csv('input/SDSS_final_revised.csv',index=False)

In [225]:
os.remove("SDSS_combined.csv")